import { Topic } from "../types";

export const AVAILABLE_TOPICS: Topic[] = [
    { id: 'space', name: 'Space', color: 'bg-blue-500' },
    { id: 'biology', name: 'Biology', color: 'bg-green-500' },
    { id: 'history', name: 'History', color: 'bg-amber-500' },
    { id: 'psychology', name: 'Psychology', color: 'bg-purple-500' },
    { id: 'technology', name: 'Technology', color: 'bg-cyan-500' },
    { id: 'physics', name: 'Physics', color: 'bg-red-500' },
    { id: 'art', name: 'Art', color: 'bg-pink-500' },
    { id: 'food', name: 'Food', color: 'bg-orange-500' },
    { id: 'astronomy', name: 'Astronomy', color: 'bg-indigo-500' },
    { id: 'geography', name: 'Geography', color: 'bg-emerald-500' },
    { id: 'literature', name: 'Literature', color: 'bg-yellow-500' },
    { id: 'music', name: 'Music', color: 'bg-rose-500' },
    { id: 'nature', name: 'Nature', color: 'bg-lime-500' },
    { id: 'culture', name: 'Culture', color: 'bg-fuchsia-500' },
    { id: 'philosophy', name: 'Philosophy', color: 'bg-violet-500' },
    { id: 'science', name: 'Science', color: 'bg-teal-500' },
    { id: 'animals', name: 'Animals', color: 'bg-orange-600' },
    { id: 'mythology', name: 'Mythology', color: 'bg-purple-600' },
    { id: 'oceans', name: 'Oceans', color: 'bg-blue-600' },
    { id: 'inventions', name: 'Inventions', color: 'bg-cyan-600' },
    { id: 'anime', name: 'Anime', color: 'bg-rose-600' },
    { id: 'coding', name: 'Coding Basics', color: 'bg-indigo-600' },
  ];